"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Patient = { id:string; name:string; age:number; sex:string; phone:string; email:string; blood:string; location:string; photo?:string };
type Result = { level:string; title:string; note:string; actions:string[]; color:string };

const symptoms = ["Fever","Headache","Cough","Chest pain","Difficulty breathing","Stomach pain","Vomiting","Diarrhoea","Dizziness","Body weakness","Skin rash","Painful urination"];
const demoPatients: Patient[] = [
  {id:"MCA-24031",name:"Ama Mensah",age:34,sex:"Female",phone:"+233 24 555 0142",email:"ama@example.com",blood:"O+",location:"Adenta, Greater Accra"},
  {id:"MCA-24032",name:"Kwame Asare",age:57,sex:"Male",phone:"+233 20 555 0188",email:"kwame@example.com",blood:"A+",location:"Madina, Greater Accra"},
  {id:"MCA-24033",name:"Akosua Boateng",age:22,sex:"Female",phone:"+233 55 555 0121",email:"akosua@example.com",blood:"B+",location:"Legon, Greater Accra"},
];

function makeQr(text:string){
  let seed=[...text].reduce((a,c)=>((a*31+c.charCodeAt(0))>>>0),2166136261); const n=21;
  const cells:Array<[number,number]> = [];
  const finder=(x:number,y:number)=>{for(let j=0;j<7;j++)for(let i=0;i<7;i++)if(i===0||j===0||i===6||j===6||(i>1&&i<5&&j>1&&j<5))cells.push([x+i,y+j]);};
  finder(0,0);finder(14,0);finder(0,14);
  for(let y=0;y<n;y++)for(let x=0;x<n;x++){seed=(seed*1664525+1013904223)>>>0;if((seed&3)===0&&!((x<8&&y<8)||(x>12&&y<8)||(x<8&&y>12)))cells.push([x,y]);}
  return <svg viewBox="0 0 21 21" aria-label={`QR code for ${text}`}><rect width="21" height="21" fill="white"/>{cells.map(([x,y],i)=><rect key={i} x={x} y={y} width="1" height="1" fill="#073b3a"/>)}</svg>;
}

export default function Home(){
  const [active,setActive]=useState("Dashboard"); const [patients,setPatients]=useState(demoPatients); const [selected,setSelected]=useState(demoPatients[0]);
  const [query,setQuery]=useState(""); const [notice,setNotice]=useState(""); const [modal,setModal]=useState<string|null>(null); const [contactOpen,setContactOpen]=useState(false); const [dark,setDark]=useState(false);
  const [message,setMessage]=useState("Hello, this is MediCare AI Hospital. This is a reminder about your healthcare appointment. Please contact the hospital if you need assistance.");
  const [subject,setSubject]=useState("Message from MediCare AI Hospital");
  const [chosen,setChosen]=useState<string[]>([]); const [details,setDetails]=useState(""); const [severity,setSeverity]=useState("Moderate"); const [days,setDays]=useState("2"); const [result,setResult]=useState<Result|null>(null);
  const [location,setLocation]=useState("Not captured"); const [photo,setPhoto]=useState(""); const video=useRef<HTMLVideoElement>(null); const stream=useRef<MediaStream|null>(null);
  useEffect(()=>{ document.documentElement.dataset.theme=dark?"dark":"light"; },[dark]);
  const filtered=useMemo(()=>patients.filter(p=>(p.name+p.id+p.phone).toLowerCase().includes(query.toLowerCase())),[patients,query]);
  function toast(m:string){setNotice(m);setTimeout(()=>setNotice(""),3200)}
  function phoneDigits(phone:string){return phone.replace(/\D/g,"").replace(/^0/,"233")}
  function openContact(patient:Patient){setSelected(patient);setContactOpen(true)}
  function assess(){
    const txt=(chosen.join(" ")+" "+details).toLowerCase(); const emergency=/chest pain|difficulty breathing|unconscious|seizure|severe bleeding|stroke|suicid/.test(txt);
    const urgent=severity==="Severe"||/high fever|blood|persistent vomiting|stiff neck/.test(txt)||selected.age<5||selected.age>65;
    if(emergency) setResult({level:"EMERGENCY",title:"Immediate clinical assessment needed",note:"The information includes a possible emergency warning sign. This tool cannot diagnose the cause.",actions:["Call Ghana emergency services on 112 or go to the nearest emergency department now.","Do not drive yourself if you feel faint, confused or severely unwell.","Show this triage summary to the receiving clinician."],color:"red"});
    else if(urgent) setResult({level:"URGENT",title:"Same-day medical review advised",note:"Your symptoms and risk factors need prompt examination by a qualified clinician. Several conditions can cause these symptoms.",actions:["Arrange a same-day hospital or clinic visit.","Keep hydrated if safe and avoid unprescribed medication.","Seek emergency help if breathing, consciousness or pain worsens."],color:"amber"});
    else setResult({level:"ROUTINE",title:"Clinical review recommended",note:"No emergency warning sign was detected from the information entered. This is triage guidance, not a diagnosis.",actions:["Book a clinician appointment within 24–72 hours if symptoms persist.","Rest, hydrate and record temperature or symptom changes.","Reassess immediately if a warning sign develops."],color:"green"});
  }
  function locate(){if(!navigator.geolocation)return toast("Location is not supported on this device."); navigator.geolocation.getCurrentPosition(p=>{const v=`${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`;setLocation(v);toast("Location captured with your permission.")},()=>toast("Location permission was not granted."),{enableHighAccuracy:true,timeout:10000});}
  async function camera(){try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"}}); if(video.current)video.current.srcObject=stream.current;}catch{toast("Camera permission was not granted.")}}
  function capture(){if(!video.current)return;const c=document.createElement("canvas");c.width=320;c.height=240;c.getContext("2d")?.drawImage(video.current,0,0,320,240);setPhoto(c.toDataURL("image/jpeg",.8));stream.current?.getTracks().forEach(t=>t.stop());toast("Live picture captured.")}
  function voice(){const W=(window as unknown as {webkitSpeechRecognition?:new()=>any;SpeechRecognition?:new()=>any}).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!W)return toast("Voice recognition is not supported in this browser.");const rec=new W();rec.lang="en-GH";rec.interimResults=false;rec.onresult=(e:any)=>{setDetails((d)=>`${d} ${e.results[0][0].transcript}`.trim());toast("Voice symptoms added.")};rec.onerror=()=>toast("Voice recognition could not complete.");rec.start();}
  function addPatient(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const p:Patient={id:`MCA-${Math.floor(10000+Math.random()*89999)}`,name:String(f.get("name")),age:Number(f.get("age")),sex:String(f.get("sex")),phone:String(f.get("phone")),email:String(f.get("email")),blood:String(f.get("blood")),location,photo};setPatients(x=>[p,...x]);setSelected(p);setModal(null);toast(`Patient ${p.name} registered successfully.`)}
  const nav=["Dashboard","Patients","AI Triage","Appointments","Clinical Records","Pharmacy","Laboratory"];
  return <main className="app-shell">
    {notice&&<div className="toast" role="status">✓ {notice}</div>}
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">✚</span><div><b>MediCare AI</b><small>Hospital OS</small></div></div>
      <nav>{nav.map(n=><button key={n} className={active===n?"active":""} onClick={()=>setActive(n)}><span>{({Dashboard:"⌂",Patients:"♙","AI Triage":"✦",Appointments:"◷","Clinical Records":"▤",Pharmacy:"⚕",Laboratory:"⌁"} as Record<string,string>)[n]}</span>{n}</button>)}</nav>
      <div className="help"><b>Need assistance?</b><p>Clinical support desk is available 24/7.</p><button onClick={()=>toast("Support request sent.")}>Contact support</button></div>
      <div className="profile"><div className="avatar">EA</div><div><b>Dr. E. Addo</b><small>Medical Officer</small></div><button>⋮</button></div>
    </aside>
    <section className="workspace">
      <header><button className="mobile-menu">☰</button><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search patient, ID or phone number…"/></div><div className="header-actions"><button onClick={()=>setDark(!dark)} aria-label="Change theme">{dark?"☀":"☾"}</button><button onClick={()=>toast("No new critical alerts.")} className="bell">♢<i/></button><button className="new-patient" onClick={()=>setModal("patient")}>＋ Register patient</button></div></header>
      <div className="content">
        {active==="Dashboard"&&<>
          <div className="welcome"><div><p>Tuesday, 11 August 2026</p><h1>Good morning, Dr. Addo</h1><span>Here is today’s clinical overview. Always verify AI guidance with a qualified clinician.</span></div><button onClick={()=>setActive("AI Triage")}>✦ Start AI triage</button></div>
          <div className="stats">{[["Total patients","1,284","+8.2%","◉"],["Appointments today","36","12 pending","◷"],["AI assessments","18","3 urgent","✦"],["Available beds","42","68% occupied","▥"]].map((s,i)=><article key={s[0]}><div className={`stat-icon i${i}`}>{s[3]}</div><div><small>{s[0]}</small><h2>{s[1]}</h2><span>{s[2]}</span></div></article>)}</div>
          <div className="grid-main">
            <article className="panel patient-list"><div className="panel-head"><div><h2>Recent patients</h2><p>Latest registrations and visits</p></div><button onClick={()=>setActive("Patients")}>View all →</button></div>
              <div className="table"><div className="tr th"><span>Patient</span><span>ID</span><span>Visit</span><span>Status</span><span></span></div>{filtered.slice(0,5).map((p,i)=><button className="tr" key={p.id} onClick={()=>{setSelected(p);setModal("card")}}><span className="patient-name"><i>{p.name.split(" ").map(x=>x[0]).join("")}</i><b>{p.name}<small>{p.sex}, {p.age} years</small></b></span><span>{p.id}</span><span>{i?"09 Aug, 2026":"Today, 09:45"}</span><span><em className={i===1?"urgent":"stable"}>{i===1?"Urgent":"Stable"}</em></span><span>›</span></button>)}</div>
            </article>
            <article className="panel schedule"><div className="panel-head"><div><h2>Today’s schedule</h2><p>11 August 2026</p></div><button onClick={()=>setActive("Appointments")}>＋</button></div>{[["09:00","Ama Mensah","Follow-up · Room 2"],["10:30","Yaw Owusu","General consultation · Room 4"],["12:00","Team rounds","Medical ward · Floor 2"],["14:30","Esi Arthur","Lab review · Virtual"]].map((x,i)=><div className="slot" key={x[0]}><time>{x[0]}</time><i className={`line l${i}`}/><div><b>{x[1]}</b><small>{x[2]}</small></div><button>⋮</button></div>)}</article>
          </div>
          <div className="lower-grid"><article className="panel alert-card"><span>!</span><div><b>Clinical safety notice</b><p>AI-generated assessments are advisory. Confirm history, vital signs, examination and tests before making any clinical decision.</p></div><button onClick={()=>toast("Safety guidance acknowledged.")}>Review protocol</button></article><article className="panel occupancy"><div><h3>Ward occupancy</h3><b>68%</b></div><div className="bar"><i/></div><small>86 of 128 beds occupied</small></article></div>
        </>}
        {active==="Patients"&&<section className="page"><div className="page-title"><div><small>PATIENT MANAGEMENT</small><h1>Patients</h1><p>Register, verify and manage patient health records.</p></div><button onClick={()=>setModal("patient")}>＋ New patient</button></div><div className="patient-cards">{filtered.map(p=><article key={p.id} onClick={()=>{setSelected(p);setModal("card")}}>{p.photo?<img src={p.photo} alt="Patient capture"/>:<i>{p.name.split(" ").map(x=>x[0]).join("")}</i>}<h3>{p.name}</h3><p>{p.id} · {p.sex}, {p.age}</p><span>{p.phone}</span><div className="card-actions"><button onClick={e=>{e.stopPropagation();openContact(p)}}>✉ Contact</button><button>Open record →</button></div></article>)}</div></section>}
        {active==="AI Triage"&&<section className="page"><div className="page-title"><div><small>CLINICAL DECISION SUPPORT</small><h1>AI-assisted symptom triage</h1><p>Collect symptoms and identify urgency. This tool does not diagnose disease.</p></div><div className="secure">◉ Clinician verification active</div></div><div className="triage-grid"><article className="panel triage-form"><h2>1. Patient and symptoms</h2><label>Patient<select value={selected.id} onChange={e=>setSelected(patients.find(p=>p.id===e.target.value)||patients[0])}>{patients.map(p=><option key={p.id} value={p.id}>{p.name} — {p.age}, {p.sex}</option>)}</select></label><div className="chips">{symptoms.map(s=><button key={s} className={chosen.includes(s)?"picked":""} onClick={()=>setChosen(x=>x.includes(s)?x.filter(v=>v!==s):[...x,s])}>{chosen.includes(s)?"✓ ":"＋ "}{s}</button>)}</div><label>Describe other symptoms<div className="voice-box"><textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="When did it start? What makes it better or worse? Include medicines, allergies and existing conditions."/><button onClick={voice} title="Use voice recognition">🎙</button></div></label><div className="two"><label>Severity<select value={severity} onChange={e=>setSeverity(e.target.value)}><option>Mild</option><option>Moderate</option><option>Severe</option></select></label><label>Duration<input type="number" min="0" value={days} onChange={e=>setDays(e.target.value)}/><small>days</small></label></div><button className="primary" onClick={assess} disabled={!chosen.length&&!details}>✦ Analyse urgency safely</button></article>
          <aside className="panel patient-summary"><div className="summary-head"><i>{selected.name.split(" ").map(x=>x[0]).join("")}</i><div><h3>{selected.name}</h3><p>{selected.id}</p></div></div><dl><div><dt>Age</dt><dd>{selected.age} years</dd></div><div><dt>Sex</dt><dd>{selected.sex}</dd></div><div><dt>Blood group</dt><dd>{selected.blood}</dd></div><div><dt>Location</dt><dd>{selected.location}</dd></div></dl>{makeQr(selected.id)}<small>Scan verified patient ID</small></aside></div>{result&&<article className={`result ${result.color}`}><div><small>{result.level} TRIAGE</small><h2>{result.title}</h2><p>{result.note}</p></div><ol>{result.actions.map(a=><li key={a}>{a}</li>)}</ol><div className="result-foot"><b>Not a medical diagnosis.</b> A licensed clinician must assess the patient.</div></article>}</section>}
        {!['Dashboard','Patients','AI Triage'].includes(active)&&<section className="page empty-page"><div className="empty-icon">{nav.indexOf(active)%2?"▤":"◷"}</div><h1>{active}</h1><p>This module is ready for hospital-specific workflows and database connection.</p><button onClick={()=>toast(`${active} sample workflow opened.`)}>Open sample workflow</button></section>}
      </div>
    </section>
    {modal&&<div className="modal-back" onMouseDown={()=>setModal(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}>×</button>{modal==="patient"?<><div className="modal-title"><small>SECURE PATIENT ONBOARDING</small><h2>Register a new patient</h2><p>Fields marked * are required. Obtain consent before camera, voice or location capture.</p></div><form onSubmit={addPatient}><div className="form-grid"><label>Full name *<input name="name" required placeholder="e.g. Kofi Mensah"/></label><label>Age *<input name="age" type="number" min="0" max="130" required/></label><label>Sex / gender *<select name="sex" required><option value="">Select</option><option>Female</option><option>Male</option><option>Intersex</option><option>Prefer not to say</option></select></label><label>Blood group<select name="blood"><option>Unknown</option><option>O+</option><option>O-</option><option>A+</option><option>A-</option><option>B+</option><option>B-</option><option>AB+</option><option>AB-</option></select></label><label>Email *<input name="email" type="email" required placeholder="patient@example.com"/></label><label>Phone number *<input name="phone" type="tel" required placeholder="+233 ..."/></label><label>Password *<input name="password" type="password" minLength={8} required placeholder="Minimum 8 characters"/></label><label>Verification code<input inputMode="numeric" pattern="[0-9]{6}" placeholder="6-digit email/SMS code"/></label></div><div className="capture-grid"><div><b>Automatic location</b><p>{location}</p><button type="button" onClick={locate}>⌖ Capture location</button></div><div><b>Live identity picture</b>{photo?<img src={photo} alt="Captured patient"/>:<video ref={video} autoPlay playsInline/>}<div><button type="button" onClick={camera}>◉ Start camera</button><button type="button" onClick={capture}>Take picture</button></div></div></div><label className="consent"><input type="checkbox" required/> Patient consent has been obtained for storing and processing this health information.</label><button className="primary" type="submit">Create secure patient record</button></form></>:<div className="id-card"><div className="modal-title"><small>VERIFIED PATIENT RECORD</small><h2>{selected.name}</h2><p>{selected.id}</p></div><div className="id-layout"><div>{selected.photo?<img src={selected.photo} alt="Patient"/>:<i>{selected.name.split(" ").map(x=>x[0]).join("")}</i>}<dl><div><dt>Age / Sex</dt><dd>{selected.age} / {selected.sex}</dd></div><div><dt>Phone</dt><dd>{selected.phone}</dd></div><div><dt>Email</dt><dd>{selected.email}</dd></div><div><dt>Location</dt><dd>{selected.location}</dd></div></dl></div><div className="big-qr">{makeQr(selected.id)}<b>{selected.id}</b><small>Secure patient identifier</small></div></div><button className="primary" onClick={()=>{setModal(null);setActive("AI Triage")}}>Start AI-assisted triage</button></div>}</div></div>}
    {contactOpen&&<div className="modal-back" onMouseDown={()=>setContactOpen(false)}><div className="modal contact-box" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setContactOpen(false)}>×</button><div className="modal-title"><small>PATIENT COMMUNICATION</small><h2>Contact {selected.name}</h2><p>Choose a channel. Your device will open the correct application with the patient and message already filled in.</p></div><div className="contact-recipient"><i>{selected.name.split(" ").map(x=>x[0]).join("")}</i><div><b>{selected.name}</b><span>{selected.phone} · {selected.email}</span></div></div><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Message<textarea value={message} onChange={e=>setMessage(e.target.value)}/></label><div className="contact-links"><a className="sms" href={`sms:${selected.phone}?body=${encodeURIComponent(message)}`}>▣ Send SMS<small>Opens phone messages</small></a><a className="email" href={`mailto:${selected.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(message)}`}>✉ Send Email<small>Opens email application</small></a><a className="whatsapp" href={`https://wa.me/${phoneDigits(selected.phone)}?text=${encodeURIComponent(message)}`} target="_blank" rel="noreferrer">◉ Send WhatsApp<small>Opens WhatsApp chat</small></a><a className="call" href={`tel:${selected.phone}`}>☎ Call Patient<small>Opens phone dialler</small></a></div><p className="contact-note">Only contact patients for authorised care purposes. Confirm consent and avoid including unnecessary sensitive medical information.</p></div></div>}
  </main>
}
